### ISSUE TITLE
2번째 피드백 및 과제

### ISSUE THREAD

**Issue by whatisand** [SullivanEducation/arduino-joystick#1]
1,2차시 개발하는것 잘 보았습니다. 역시 여러번 경험이 있으니까 잘 하시는 것 같아요.

생각만 해보는 것도 좋지만 그 과정을 커리큘럼에 남겨주세요.
(+ 피드백 부분에 질문도 같이 적어주세요ㅠㅠ 어떤 피드백을 남겼는지 커리큘럼 담당자와 여러분밖에 모릅니다ㅠㅠ)

이번에도 교육 피드백보단, 몇가지 과제를 드리도록 하겠습니다.
이번에는 1번만 한다고 생각하고, 다음주 월요일까지 찾을 수 있는 만큼 찾아보시면 됩니다.

1. 기존에 있던 조이스틱 만들기 교육, 또는 비슷한 컨샙의 교육은 어느것이 있는지 찾아보고, 똑같거나 가장 비슷한거 하나 고르기
- 지금 1,2차시 참고에 적어두신 것 처럼 유튜브도 좋고요,
- 한차시 또는 단발성 유료교육,
- 학원 커리큘럼도 좋습니다.

2. 똑같거나 가장 비슷하다고 생각한 교육은 어떤게 문제일지?
3. 그것과 여러분이 만드는 교육과 비교했을때, 우리는 어떤부분이 더 좋고, 어떤부분이 더 안좋은지?

정도입니다.

일단 1번에 대한 것만 해보고 담당자분께 알려주세요.

감사합니다.

**Comment by hyemdooly** [comment]
여러분의 담당자는 저입니다..!
여러 번 교육을 나가본 친구들이 많아서 그런지 잘하셔서, 제가 더 피드백 할 사항은 없는 것 같아요! :)
과제 해보시고 여기 이슈 코멘트로 달아주세요~~
3차시 기획서는 9월 14일까지 제출해주세요!

**Comment by inkyulee79** [comment]
저희가 조사한 사이트는 다음과 같습니다!
- - -

## 오프라인 강의 & 키트 판매 회사

- [헬로앱스](https://www.helloapps.co.kr/education/)  
교육의 퀄리티는 그렇게 좋다는 생각은 안들지만, 자료들이 알차게 구성이되어있는 것 같다. ex) pdf파일들이 많이 있다. 체계적이고, 전반적인 아두이노 교육들의 기본을 다질 수 있는 것 같다. 강의라는 크게 관련성은 없다.


## 유튜브

- [Bluetooth game controller (Joystick) with Arduino and Jetpack](https://www.youtube.com/watch?v=J33fkEGaGlA)  
 브레드보드까지 활용해서 한손으로 들고 조종할 수 있는 조이스틱을 가지고, 시연해 보는 영상이다. 만드는 과정은 나와 있지 않고, 게임 시연 영상만 나와 있다.

- [Joystick movement and animation with Unity and Arduino Leonardo](https://www.youtube.com/watch?v=HlffCAp7CK4)  
브래드 보드를 사용 하지 않고, 조이스틱의 손잡이 부분을 나무로 크게 만들어서 좀 더 작동하기 쉽게 끔 만든 조이스틱이다. 제작 과정은 나와 있지 않고, 시연 영상만 나와있다.

- [Arduino wireless gamepad (UnoJoy)](https://www.youtube.com/watch?v=cZc-23NjNHY)  
레오나르도를 사용하여 조이스틱을 이용해 드론 게임을 해보기

- [**DIY ARDUINO MOUSE JOYSTICK**](https://www.youtube.com/watch?v=t8mE1ayw5bo)  
우리의 커리큘럼과 상당히 흡사하다. 아두이노 레오나르도를 이용해 Mouse, Keyboard 함수를 사용해서, USB를 통해 PC 게임을 조종할 수 있는 것까지 비슷하다. 코드와 회로 원리에 대한 설명이 미흡한 것 같다.
	
- [jPAint+Arduino Leonardo+Joystick prova1](https://www.youtube.com/watch?v=YJkK0OfiENs)  
아두이노 레오나르도를 사용하여 그림 그려보기

## 온라인강좌

- [정글코딩: 로봇을 움직이는 조이스틱 만들기](http://junglecoding.com/2018/01/23/03-%EB%B9%84%ED%8A%B8%EB%B8%8C%EB%A6%AD-%EB%A1%9C%EB%B4%87-%EC%A1%B0%EC%9D%B4%EC%8A%A4%ED%8B%B1-%EB%A7%8C%EB%93%A4%EA%B8%B0/)  
비트브릭이다.

- [Korea SW](http://koreasw.org/?p=736)  
→  마인크래프트에서 사용할 수 있는 조이스틱을 만들 수 있도록 기초부터 도와주는 단편 인터넷 동영상 강의이고, 조이스틱 모듈을 사용하지 않고 버튼을 브레드보드에 배치하여 조이스틱과 비슷한 모양을 만든다.

- [인프런](https://www.inflearn.com/course/%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8-%EA%B0%95%EC%A2%8C/#course-curriculum)  
전체적인 아두이노 기본교육, 기본적인 기술들에대한 강의들이 들어가있다. (우리의 프로젝트와 큰 연관성은 없다)


- [코코아팹](https://kocoafab.cc/make/view/638)  
DIY 조이스틱 만들기로 줄글로 된 튜토리얼과 전체 소스코드가 공개된다. 구비해야하는 센서와 보드 또한 나타나져 있고, 영상으로 된 자료는 없다. 

- [코코아팹](https://www.kocoafab.cc/tutorial/view/384)  
개요, 부품목록, 활동 전 개념, 만들기, 순서도 등 활동하기 위한 튜토리얼이 기재되어 있다. 스크래치를 사용하였다.

- - -

### 저희가 선택한 커리큘럼은 [DIY ARDUINO MOUSE JOYSTICK](https://www.youtube.com/watch?v=t8mE1ayw5bo) 입니다!

**Comment by hyemdooly** [comment]
정말 자세하게 조사를 잘해주셨네요! :)
이 이슈는 닫을게요. 다음 피드백에서 2번에 대해 생각해보도록 합시다. 👍

**Comment by hyemdooly** [comment]
정말 자세하게 조사를 잘해주셨네요! :)
이 이슈는 닫을게요. 다음 피드백에서 2번에 대해 생각해보도록 합시다. 👍
